### ISSUE TITLE
Should trillspell add an editorial marker (x)?

### ISSUE THREAD

**Issue by pvankranenburg** [craigsapp/humlib#12]
Tranks again for adding the trillspell filter.
Since after running this filter all trills can be considered 'interpreted', wouldn't it be better to add an `x` directly after the ornament?

**Comment by craigsapp** [comment]
I just added an `-x` option that adds an `x` directly after the ornament:

```bash
trillspell -x file.krn > file2.krn
```

Other updates to the trillspell program:

If the ornament already has an `x` after it, another will not be added.

If there already is an `x` after the ornament, the trillspell program will not try to alter the ornament interval.
