### ISSUE TITLE
Add system grouping information

### ISSUE THREAD

**Issue by jacekiwaszko1** [craigsapp/humlib#20]
An alternate system for system decroration would be useful to add as illustrated in the following example:

![groups-system-decoration](https://user-images.githubusercontent.com/29225574/69416291-934d9c00-0d16-11ea-8cde-480fb33865e7.png)

```
**kern	**kern	**kern	**kern	**kern
*group2	*group2	*group1	*group1	*group1
*staff5	*staff4	*staff3	*staff2	*staff1
=	=	=	=	=
1C	1G	1c	1g	1cc
==	==	==	==	==
*-	*-	*-	*-	*-
!!!system-decoration: [(s1,s2,s3)],[(s4,s5)]
```

Notice the `*group` line: there are two groups, and these groups would be automatically beamed together as a group on the system without the need for the system-decoration instruction.

This would be useful as an alternate to the `!!!system-decoration:` system, not necessarily as a replacement. 

When extracting music the `*group` information can be used to control the beaminging of staves.

Another idea is to allow for system-decoration to work on the group level, such as:

```
!!!system-decoration: [g1][g2]
```

`g1` would automatically be identified and expanded to `(s1, s2, s3)` for example.

**Comment by craigsapp** [comment]
This was implemented a while ago.  For the system decoration, the string for group encoding is:

```
!!!system-decoration: [(g1)][(g2)]
```

<img width="1430" alt="Screen Shot 2020-03-11 at 10 28 53 PM" src="https://user-images.githubusercontent.com/3487289/76490238-d6c43700-63e7-11ea-81c6-2d6e5c7eb52c.png">

The parentheses will add barlines connecting the staves.  Without the parentheses, the staves in the group are not connected by the barlines:

<img width="1430" alt="Screen Shot 2020-03-11 at 10 30 46 PM" src="https://user-images.githubusercontent.com/3487289/76490293-f9565000-63e7-11ea-89f8-f53ca31a9a7e.png">
