### ISSUE TITLE
Remove sudo in Makefile.programs

### ISSUE THREAD

**Issue by WolfgangDrescher** [craigsapp/humlib#49]
Is `sudo` really needed here? This throws an error creating humlib in an `alpine` Docker image. I could of course just run `apk add sudo`, but since it is not recommended to add this into a Docker container maybe it's worth checking if `sudo` is really necessary here:

https://github.com/craigsapp/humlib/blob/8e9bb97435c189e901fcc114da074eb3da7e0372/Makefile.programs#L103

Here is the Dockerfile im using: https://github.com/WolfgangDrescher/humdrum-docker-image/blob/master/Dockerfile

Error log:

```
 => [20/21] RUN make
 => ERROR [21/21] RUN make install
------
 > [21/21] RUN make install:
#25 0.619 make[1]: Entering directory '/usr/local/humlib'
#25 1.836 strip: makehumlib: file format not recognized
#25 2.640 /bin/sh: sudo: not found
#25 2.641 make[1]: Leaving directory '/usr/local/humlib'
#25 2.641 make[1]: *** [Makefile.programs:103: install] Error 127
#25 2.642 make: *** [Makefile:176: install] Error 2
------
executor failed running [/bin/sh -c make install]: exit code: 2
```

**Comment by craigsapp** [comment]
I have had problems with not using `sudo` on various flavors of unix/linux.   Technically `/usr/local/bin` should not be writable by anyone except root (and by extension by members of the `wheel` group who can use sudo).   If `/usr/local/bin` were accessible to anyone, then if a hacker were able to gain access to any account on the computer, they could add/modify programs in that directory.

I could add make targets for non-sudo variants, such as `make install-nosudo` in this case.

> /bin/sh: sudo: not found

An alternate possibility is to check if `sudo` command is available, and not use it if it is not found (this would fix your case most likely, particularly if you are already running as root).  And/or if `root` is installing, then obviously `sudo` is not needed.

**Comment by WolfgangDrescher** [comment]
> I could add make targets for non-sudo variants, such as make install-nosudo in this case.

Thank you, but I think it is not needed to add an additional make command since it's easy to just add `apk add sudo` in my case. Since you had problems without `sudo` I will just stick with it.

**Comment by craigsapp** [comment]
OK, but no problem to add or adjust other aspects of the makefile if needed.
