### ISSUE TITLE
`make` command fails to build

### ISSUE THREAD

**Issue by WolfgangDrescher** [craigsapp/humlib#78]
I used to build and debug a specific tool with `make library && make fb`. However, it seems that recent changes in the Makefile changed this: https://github.com/craigsapp/humlib/commit/3c7d24fb1fa52a673fc67c23d35be5b772e56f9a

When I run `make` I get the following output:

```
ar: creating archive lib/libhumlib.a
[CC] accent-features
[CC] activevoices
[CC] alignXywh
[CC] autoaccid
cli/autoaccid.cpp:16:1: error: expected ')'
STREAM_INTERFACE(Tool_autoaccid)
^
min/humlib.h:5313:38: note: expanded from macro 'STREAM_INTERFACE'
        if (interface.getBoolean("options") {                         \
                                            ^
cli/autoaccid.cpp:16:1: note: to match this '('
min/humlib.h:5313:5: note: expanded from macro 'STREAM_INTERFACE'
        if (interface.getBoolean("options") {                         \
           ^
cli/autoaccid.cpp:16:1: error: use of undeclared identifier 'instream'
STREAM_INTERFACE(Tool_autoaccid)
^
min/humlib.h:5319:9: note: expanded from macro 'STREAM_INTERFACE'
        while (instream.readSingleSegment(infiles)) {                 \
               ^
2 errors generated.
make[1]: *** [autoaccid] Error 1
make: *** [programs] Error 2
```

Is there a new command that I am missing to build the full humlib and/or just one tool?

**Comment by craigsapp** [comment]
AppVeyor is happy: https://ci.appveyor.com/project/craigsapp/humlib/builds/46940109

(although it does not compile the tools, where the error was happening).   I forgot to add the `ordergps` tool to the first submit just now, but after adding the files to the repository, it is compiling correctly for me.
